/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package realworldsoftwaredevelopment;

import realworldsoftwaredevelopment.bankAnalzyer.BankAnalzyer;

public class App {
    private static final String RESOURCES_URL = "app/src/main/resources/";
    private static final String FILE_NAME = "BankStatement.csv";

    public static void main(String[] args) throws Exception{
        BankAnalzyer bankAnalzyer = new BankAnalzyer();
        bankAnalzyer.analyze(RESOURCES_URL + FILE_NAME);
    }
}
